# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.0.1
maven_group = com.github.zahisuku.powergrid_illuminations
archives_name = powergrid_illuminations
enabled_platforms = neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.11
fabric_loader_version = 0.19.5
fabric_api_version = 0.116.15+1.21.1
neoforge_version = 21.1.248

# create, ponder, flywheel, registrate
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67