modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "powergrid_illuminations"
version = "${version}"
displayName = "Create: PowerGrid - Illuminations"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.powergrid_illuminations]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.powergrid_illuminations]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.powergrid_illuminations]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.powergrid_illuminations]]
modId = "powergrid"
type = "required"
versionRange = "[0.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "powergrid_illuminations.mixins.json"
